export { default as Assignments } from "./Assignments";
export { default as Classmates } from "./Classmates";
export { default as Home } from "./Home";
export { default as Leaderboard } from "./Leaderboard";
export { default as Courses } from "./Courses";
export { default as Visualization } from "./Visualization";
export { default as Calendar } from "./Calendar";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
